### ISSUE TITLE
EJS templating breaks build

### ISSUE THREAD

**Issue by cmegown** [joezimjs/Webpack-Introduction-Tutorial#1]
When I got the "[Using Plugins](https://www.smashingmagazine.com/2017/02/a-detailed-introduction-to-webpack/#using-plugins)" part of the article I had to remove the EJS templating in the `<title>` tag to get the project to build.

Note: I'm also on Windows, and as this is my first time really digging into the mechanics of webpack so there shouldn't be anything interfering from my setup.

Here's the error I'm receiving:
```
ERROR in Template execution failed: ReferenceError: htmlwebpackPlugin is not def
ined

ERROR in   ReferenceError: htmlwebpackPlugin is not defined

  - index.html:17224
    C:/Users/cpm/Desktop/temp/webpack-intro/src/index.html:17224:11

  - index.html:17227 module.exports
    C:/Users/cpm/Desktop/temp/webpack-intro/src/index.html:17227:3

  - index.js:265
    [webpack-intro]/[html-webpack-plugin]/index.js:265:16

  - util.js:16 tryCatcher
    [webpack-intro]/[bluebird]/js/release/util.js:16:23

  - promise.js:510 Promise._settlePromiseFromHandler
    [webpack-intro]/[bluebird]/js/release/promise.js:510:31

  - promise.js:567 Promise._settlePromise
    [webpack-intro]/[bluebird]/js/release/promise.js:567:18

  - promise.js:604 Promise._settlePromiseCtx
    [webpack-intro]/[bluebird]/js/release/promise.js:604:10

  - async.js:138 Async._drainQueue
    [webpack-intro]/[bluebird]/js/release/async.js:138:12

  - async.js:143 Async._drainQueues
    [webpack-intro]/[bluebird]/js/release/async.js:143:10

  - async.js:17 Immediate.Async.drainQueues
    [webpack-intro]/[bluebird]/js/release/async.js:17:14
```

**Comment by joezimjs** [comment]
It looks to me like a typo of the plugin name. The errors are saying "htmlwebpackPlugin is not defined". However, I can't know for sure unless I see your webpack.config.js file.

**Comment by joezimjs** [comment]
Oh, actually, it looks like it's actually happening in the index.html file. Note that you didn't capitalize the W in `htmlWebpackPlugin`.

**Comment by joezimjs** [comment]
I've fixed the typo in the tutorial on SM now.

**Comment by cmegown** [comment]
I just checked the updated syntax in the article and everything ran smoothly. Thanks!
